#!/usr/bin/env python3
"""
Hermes Dynamic Roster Sidecar
==============================

Lightweight daemon that polls OpenRouter for free models every 5 minutes
and writes the best candidates to a YAML include file consumed by LiteLLM.

Extracted from router_server.py:
  - _is_reasoning_model()  (L103-120)
  - _background_model_fetch() (L122-176)

Strategy: Write dynamic models to ~/.hermes/dynamic_models.yaml which is
included by the main litellm_config.yaml. After updating the file, send
SIGUSR1 to LiteLLM to trigger a graceful config reload.

Run as a launchd daemon:
  ~/.hermes/venv_router/bin/python3 ~/.hermes/skills/dynamic_roster_sidecar.py
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

import urllib.request
import urllib.error

# ─── Configuration ───────────────────────────────────────────────────────────
import os
_HERMES_DIR = Path(os.environ.get("FRUGALLM_CONFIG_DIR", Path.cwd() / "config"))
_ENV_PATH = _HERMES_DIR / ".env"
_DYNAMIC_MODELS_PATH = _HERMES_DIR / "dynamic_models.yaml"
_LITELLM_PID_PATTERN = "litellm"

POLL_INTERVAL = 300  # 5 minutes
OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"

# ─── Logging ─────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [Sidecar] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("hermes-roster-sidecar")

# ─── Environment Loading ────────────────────────────────────────────────────
def _load_env():
    """Load .env file into os.environ (same pattern as router_server.py)."""
    if not _ENV_PATH.exists():
        return
    for line in _ENV_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        k = key.strip()
        v = value.strip().strip('"').strip("'")
        if k and k not in os.environ:
            os.environ[k] = v


_load_env()

# Use the dedicated management key if available, else fall back to inference key
OPENROUTER_API_KEY = os.getenv(
    "OPENROUTER_MANAGEMENT_KEY", os.getenv("OPENROUTER_API_KEY", "")
)
# The inference key for the dynamic models (always use the standard key)
OPENROUTER_INFERENCE_KEY = os.getenv("OPENROUTER_API_KEY", "")

# ─── State Tracking ─────────────────────────────────────────────────────────
_current_balanced: list[str] | None = None
_current_reasoning: list[str] | None = None


# ═══════════════════════════════════════════════════════════════════════════════
# Extracted Logic from router_server.py (VERBATIM)
# ═══════════════════════════════════════════════════════════════════════════════

def _is_reasoning_model(model_data: dict) -> bool:
    """
    Agnostic heuristic to detect reasoning models based on metadata.

    Extracted from router_server.py L103-120 (VERBATIM).
    """
    m_id = model_data.get("id", "").lower()
    m_name = model_data.get("name", "").lower()
    m_desc = model_data.get("description", "").lower()

    search_space = f"{m_id} {m_name} {m_desc}"
    keywords = [
        "reasoning",
        "chain-of-thought",
        "-cot-",
        "thinker",
        "thought process",
    ]

    # Check for direct heuristic keywords
    if any(kw in search_space for kw in keywords):
        return True

    # Generic matching for models that commonly include "think" or "reason" in the raw ID
    if any(kw in m_id for kw in ("-reason", "think", "-o1", "-r1")):
        return True

    return False


# ═══════════════════════════════════════════════════════════════════════════════
# YAML File Writer (replaces Management API)
# ═══════════════════════════════════════════════════════════════════════════════

def _write_dynamic_models(balanced_ids: list[str], reasoning_ids: list[str]) -> bool:
    """
    Write the dynamic model definitions to a YAML include file using fallback chaining.

    IMPORTANT: This file is the SINGLE SOURCE OF TRUTH for all router_settings,
    including fallbacks. LiteLLM's include: mechanism OVERWRITES (not merges)
    router_settings between files. If any router_settings exist in litellm_config.yaml,
    they will be silently dropped when this file is loaded.

    See: 2026-07-22 thinker 503 incident — all pseudo-model alias fallbacks were
    missing because they were defined in litellm_config.yaml and overwritten by
    this file's router_settings.
    """
    def _litellm_model(or_id: str) -> str:
        if or_id.startswith("openrouter/") or or_id.startswith("ollama/") or or_id.startswith("openai/"):
            return or_id
        return f"openrouter/{or_id}"

    yaml_lines = [
        "# ═══════════════════════════════════════════════════════════════════════════════",
        "# AUTO-GENERATED by dynamic_roster_sidecar.py — DO NOT EDIT MANUALLY",
        f"# Last updated: {time.strftime('%Y-%m-%d %H:%M:%S %Z')}",
        "# ═══════════════════════════════════════════════════════════════════════════════",
        "",
        "model_list:"
    ]

    # ── Static fallbacks for pseudo-model aliases and core models ──
    # These MUST live here (not in litellm_config.yaml) because LiteLLM's
    # include: mechanism overwrites router_settings rather than merging them.
    fallbacks = [
        "    # ── Pseudo-Model Alias Fallbacks ──",
        '    - {"frugal": ["free_balanced", "gemini-flash"]}',
        '    - {"smart": ["free_balanced", "gemini-flash"]}',
        '    - {"thinker": ["free_reasoning", "gemini-flash"]}',
        '    - {"reasoner": ["free_reasoning", "gemini-flash"]}',
        '    - {"offline": ["free_balanced", "gemini-flash"]}',
        '    - {"private": ["free_balanced", "gemini-flash"]}',
        '    - {"cloud": ["gemini-flash"]}',
        '    - {"fast": ["gemini-flash-lite"]}',
        '    - {"lite": ["gemini-flash-lite"]}',
        '    - {"free": ["free_balanced", "gemini-flash"]}',
        "    # ── Core Model Fallbacks ──",
        '    - {"auto": ["free_balanced", "gemini-flash"]}',
        '    - {"reasoning": ["free_reasoning", "gemini-flash"]}',
        '    - {"local": ["free_balanced", "gemini-flash"]}',
        "    # ── Dynamic Free Model Chains (generated) ──",
    ]

    # Generate Balanced Chain
    yaml_lines.append("  # ── Balanced Chain ──")
    for i, b_id in enumerate(balanced_ids):
        model_name = "free_balanced" if i == 0 else f"free_balanced_{i+1}"
        yaml_lines.extend([
            f"  - model_name: {model_name}",
            "    litellm_params:",
            f"      model: {_litellm_model(b_id)}",
            "      api_key: os.environ/OPENROUTER_API_KEY",
            "      max_tokens: 8192",
            "      timeout: 35",
            "      max_retries: 0",
            ""
        ])
        if i < len(balanced_ids) - 1:
            next_model = f"free_balanced_{i+2}"
            fallbacks.append(f"    - {{\"{model_name}\": [\"{next_model}\"]}}")
        else:
            fallbacks.append(f"    - {{\"{model_name}\": [\"free_balanced_backup\"]}}")

    yaml_lines.extend([
        "  - model_name: free_balanced_backup",
        "    litellm_params:",
        "      model: gemini/gemini-3.6-flash",
        "      api_key: os.environ/GOOGLE_API_KEY",
        "      max_tokens: 8192",
        "      timeout: 120",
        "      max_retries: 0",
        ""
    ])

    # Generate Reasoning Chain
    yaml_lines.append("  # ── Reasoning Chain ──")
    for i, r_id in enumerate(reasoning_ids):
        model_name = "free_reasoning" if i == 0 else f"free_reasoning_{i+1}"
        yaml_lines.extend([
            f"  - model_name: {model_name}",
            "    litellm_params:",
            f"      model: {_litellm_model(r_id)}",
            "      api_key: os.environ/OPENROUTER_API_KEY",
            "      max_tokens: 8192",
            "      timeout: 35",
            "      max_retries: 0",
            ""
        ])
        if i < len(reasoning_ids) - 1:
            next_model = f"free_reasoning_{i+2}"
            fallbacks.append(f"    - {{\"{model_name}\": [\"{next_model}\"]}}")
        else:
            fallbacks.append(f"    - {{\"{model_name}\": [\"free_reasoning_backup\"]}}")

    yaml_lines.extend([
        "  - model_name: free_reasoning_backup",
        "    litellm_params:",
        "      model: gemini/gemini-3.6-flash",
        "      api_key: os.environ/GOOGLE_API_KEY",
        "      max_tokens: 8192",
        "      timeout: 120",
        "      max_retries: 0",
        ""
    ])

    # ── Full router_settings block ──
    # This is the SINGLE SOURCE OF TRUTH for all router settings.
    yaml_lines.extend([
        "router_settings:",
        "  allowed_fails: 3",
        "  num_retries: 2",
        "  retry_after: 60",
        "  routing_strategy: simple-shuffle",
        "  stream_timeout: 300",
        "  timeout: 300",
        "  fallbacks:"
    ])
    yaml_lines.extend(fallbacks)
    yaml_lines.append("")

    yaml_content = "\n".join(yaml_lines)

    try:
        # Atomic write: write to temp, then rename
        tmp_path = _DYNAMIC_MODELS_PATH.with_suffix(".tmp")
        tmp_path.write_text(yaml_content)
        tmp_path.rename(_DYNAMIC_MODELS_PATH)
        log.info(f"✓ Wrote dynamic_models.yaml (balanced={len(balanced_ids)}, reasoning={len(reasoning_ids)}, fallback_entries={len(fallbacks)})")
        return True
    except Exception as e:
        log.error(f"Failed to write dynamic_models.yaml: {e}")
        return False


def _restart_litellm():
    """
    Restart the LiteLLM proxy to pick up the new config include.
    Uses SIGHUP for a zero-downtime config reload, falling back to launchctl.
    """
    try:
        if _signal_litellm():
            log.info("✓ LiteLLM config reloaded via SIGHUP.")
            return True
        else:
            log.warning("SIGHUP failed, falling back to launchctl kickstart...")
            result = subprocess.run(
                ["launchctl", "kickstart", "-k", f"gui/{os.getuid()}/com.hermes.router-proxy"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                log.info("✓ LiteLLM proxy restart triggered via launchctl.")
                return True
            else:
                log.error(f"launchctl kickstart returned {result.returncode}: {result.stderr.strip()}")
                return False
    except Exception as e:
        log.error(f"Restart failed entirely: {e}")
        return False


def _signal_litellm() -> bool:
    """Fallback: find LiteLLM PID and send SIGHUP."""
    try:
        result = subprocess.run(
            ["pgrep", "-f", "litellm.*--config"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            for pid_str in result.stdout.strip().split("\n"):
                pid = int(pid_str.strip())
                os.kill(pid, signal.SIGHUP)
                log.info(f"✓ Sent SIGHUP to LiteLLM PID {pid}")
            return True
        else:
            log.warning("Could not find LiteLLM process for SIGHUP.")
            return False
    except Exception as e:
        log.error(f"Failed to signal LiteLLM: {e}")
        return False


def _wait_for_litellm() -> bool:
    """Wait for LiteLLM to become available (up to 300 seconds).
    Uses /v1/models instead of /health because /health probes all backends
    (including unreachable ones like offline Qwen) causing long timeouts.
    """
    # Inside Docker: FRUGALLM_PROXY_PORT=4000, hostname=litellm
    # On host: defaults to 127.0.0.1:5050 (Gatekeeper port)
    proxy_port = os.getenv("FRUGALLM_PROXY_PORT", "5050")
    proxy_host = os.getenv("FRUGALLM_PROXY_HOST", "127.0.0.1")
    # If running in Docker (port 4000), use the Docker service name
    if proxy_port == "4000" and proxy_host == "127.0.0.1":
        proxy_host = "litellm"
    proxy_url = f"http://{proxy_host}:{proxy_port}/v1/models"

    log.info(f"⏳ Waiting for LiteLLM proxy at {proxy_url}...")
    for attempt in range(60):
        try:
            req = urllib.request.Request(
                proxy_url,
                headers={"Authorization": "Bearer sk-sidecar-1"},
            )
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 200:
                    log.info("✓ LiteLLM proxy is online.")
                    return True
        except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError):
            pass
        time.sleep(5)

    log.error("✗ LiteLLM proxy did not become available after 300s.")
    return False


# ═══════════════════════════════════════════════════════════════════════════════
# Main Discovery Loop (adapted from _background_model_fetch)
# ═══════════════════════════════════════════════════════════════════════════════

def discover_and_register():
    """
    Polls OpenRouter for free models, classifies them, and writes the
    best ones to the dynamic_models.yaml include file.

    Adapted from router_server.py L122-176.
    """
    global _current_balanced, _current_reasoning

    # Fallback model IDs (must be free models!)
    FALLBACK_BALANCED = ["google/gemini-2.5-flash:free", "google/gemini-pro"]
    FALLBACK_REASONING = ["google/gemini-2.5-pro:free", "google/gemini-pro"]

    best_balanced = FALLBACK_BALANCED
    best_reasoning = FALLBACK_REASONING

    try:
        log.info("☀ Scanning OpenRouter for the best free models...")

        headers = {}
        if OPENROUTER_API_KEY:
            headers["Authorization"] = f"Bearer {OPENROUTER_API_KEY}"

        req = urllib.request.Request(OPENROUTER_MODELS_URL, headers=headers)
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8")).get("data", [])

        # Filter free models that support tool use
        free = []
        for m in data:
            params = m.get("supported_parameters", [])
            if "tools" not in params:
                continue
                
            p = m.get("pricing", {})
            try:
                if (
                    float(p.get("prompt", "1")) == 0
                    and float(p.get("completion", "1")) == 0
                ):
                    free.append(m)
            except (ValueError, TypeError):
                continue

        # Sort all free models by created to find the newest ones
        free.sort(key=lambda x: x.get("created", 0), reverse=True)

        if free:
            # We filter for 256k+ context for both balanced and reasoning pools
            free_balanced_models = [m for m in free if m.get("context_length", 0) >= 256000]
            if not free_balanced_models:
                free_balanced_models = free  # Fallback to any context length if none >= 256k
                
            best_balanced = [m["id"] for m in free_balanced_models]
            log.info(f"✓ free_balanced candidates: {len(best_balanced)} models")

            # Agnostically search the pool for reasoning models with >=256k context
            reasoning_models = [
                m for m in free
                if _is_reasoning_model(m) and m.get("context_length", 0) >= 256000
            ]

            if reasoning_models:
                best_reasoning = [m["id"] for m in reasoning_models]
                log.info(f"✓ free_reasoning candidates: {best_reasoning}")
            else:
                log.info(
                    "ℹ No dedicated free reasoning model found with >=256k context. "
                    "Falling back reasoning route to balanced pool."
                )
                best_reasoning = best_balanced

        log.info(f"Free pool size: {len(free)} models available.")

    except Exception as e:
        log.warning(f"OpenRouter fetch failed, using fallbacks: {e}")

    # Only update config and restart if the models have changed
    if best_balanced != _current_balanced or best_reasoning != _current_reasoning:
        if _write_dynamic_models(best_balanced, best_reasoning):
            _current_balanced = best_balanced
            _current_reasoning = best_reasoning
            log.info("🔄 Roster changed — restarting LiteLLM to load new models...")
            _restart_litellm()
            # Wait for LiteLLM to come back online after restart
            time.sleep(5)
            _wait_for_litellm()
        else:
            log.error("Failed to write dynamic models — skipping restart.")
    else:
        log.info("No roster changes needed.")


def main():
    """Main daemon loop."""
    print(
        f"""
╔══════════════════════════════════════════════════════════════╗
║     HERMES DYNAMIC ROSTER SIDECAR                           ║
╠══════════════════════════════════════════════════════════════╣
║  Config Target:   {_DYNAMIC_MODELS_PATH}
║  Poll Interval:   {POLL_INTERVAL}s ({POLL_INTERVAL // 60} minutes)
║  OpenRouter Key:  {'✓ Present' if OPENROUTER_API_KEY else '✗ MISSING'}
║  Waiting for LiteLLM to come online...
╚══════════════════════════════════════════════════════════════╝
"""
    )

    # Wait for LiteLLM to be ready before starting the loop
    if not _wait_for_litellm():
        log.error("Exiting: LiteLLM proxy is not available.")
        sys.exit(1)

    # Initial discovery
    discover_and_register()

    # Polling loop
    while True:
        try:
            time.sleep(POLL_INTERVAL)
            discover_and_register()
        except KeyboardInterrupt:
            log.info("Shutting down sidecar.")
            break
        except Exception as e:
            log.error(f"Unexpected error in sidecar loop: {e}")
            time.sleep(30)  # Back off on unexpected errors


if __name__ == "__main__":
    main()
